USE [HakopLibraryDB]
GO
/****** Object:  Table [dbo].[LibraryTable]    Script Date: 3/28/2021 3:42:17 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LibraryTable](
	[Name] [nvarchar](max) NOT NULL,
	[Location] [geography] NOT NULL,
	[LibraryID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_LibraryTable] PRIMARY KEY CLUSTERED 
(
	[LibraryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
