USE [master]
GO
/****** Object:  Database [HakopLibraryDB]    Script Date: 5/9/2021 5:32:30 PM ******/
CREATE DATABASE [HakopLibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HakopLibraryDB', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HakopLibraryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HakopLibraryDB_log', FILENAME = N'D:\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HakopLibraryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [HakopLibraryDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HakopLibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [HakopLibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [HakopLibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [HakopLibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [HakopLibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [HakopLibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET RECOVERY FULL 
GO
ALTER DATABASE [HakopLibraryDB] SET  MULTI_USER 
GO
ALTER DATABASE [HakopLibraryDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [HakopLibraryDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [HakopLibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [HakopLibraryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [HakopLibraryDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [HakopLibraryDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'HakopLibraryDB', N'ON'
GO
ALTER DATABASE [HakopLibraryDB] SET QUERY_STORE = OFF
GO
ALTER DATABASE [HakopLibraryDB] SET  READ_WRITE 
GO
